services:
  - type: web
    name: dispominera
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: USE_ATHENA
        value: true
      - key: FLASK_ENV
        value: production
    plan: free
